<a href="https://colab.research.google.com/github/otworiallan/otworiallan/blob/main/Python__Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
x = torch.tensor([1.,5,6,7,4])
x.dtype

torch.float32

In [26]:
random_tensor_A = torch.rand(size=(7,7), device="cpu")
random_tensor_A

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])

In [27]:
random_tensor_B = torch.rand(size=(1,7), device="cpu")
random_tensor_B

tensor([[0.7213, 0.4414, 0.5550, 0.6361, 0.1081, 0.3305, 0.5196]])

In [28]:
#Multiplying the Two random Tensors
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result, result.shape

(tensor([[1.6914],
         [1.7581],
         [2.0906],
         [1.8975],
         [1.7585],
         [1.7961],
         [1.8900]]),
 torch.Size([7, 1]))

In [39]:
torch.manual_seed(0)
random_tensor_C = torch.rand(size=(7,7), device="cpu")
random_tensor_C

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [42]:
torch.manual_seed(0)
random_tensor_D = torch.rand(size=(1,7), device="cpu")
random_tensor_D

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [43]:
result = torch.matmul(random_tensor_C, random_tensor_D.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [9]:
result.device

device(type='cpu')

#Random Seed on GPU


In [10]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [13]:
torch.cuda.manual_seed(1243)

random_tensor_E = torch.rand(size=(2,3), device=device)
random_tensor_E, random_tensor_E.device


(tensor([[0.3465, 0.0589, 0.5064],
         [0.7421, 0.7305, 0.9400]], device='cuda:0'),
 device(type='cuda', index=0))

In [14]:
torch.cuda.manual_seed(1234)
random_tensor_F = torch.rand(size=(2,3), device=device)
random_tensor_F, random_tensor_F.device

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 device(type='cuda', index=0))

In [16]:
result = torch.matmul(random_tensor_E, random_tensor_F.T)
result, result.size()

(tensor([[0.3676, 0.7378],
         [1.2024, 1.6039]], device='cuda:0'),
 torch.Size([2, 2]))

In [17]:
torch.max(result), result.max()

(tensor(1.6039, device='cuda:0'), tensor(1.6039, device='cuda:0'))

In [18]:
torch.min(result), result.min()

(tensor(0.3676, device='cuda:0'), tensor(0.3676, device='cuda:0'))

In [23]:
torch.manual_seed(7)
random_tensor_G = torch.rand(size=(1,1,1,10), device="cpu")
random_tensor_G

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [25]:
#squeeze random_tensor_G
random_tensor_G.squeeze(), random_tensor_G.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))