<a href="https://colab.research.google.com/github/otworiallan/otworiallan/blob/main/Python__Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [10]:
x = torch.tensor([1.,5,6,7,4])
x.dtype

torch.float32

In [13]:
random_tensor_A = torch.rand(size=(7,7))
random_tensor_A

tensor([[0.9196, 0.7039, 0.4841, 0.6472, 0.2575, 0.1188, 0.4076],
        [0.6740, 0.0353, 0.8693, 0.5246, 0.5453, 0.7737, 0.4276],
        [0.1809, 0.7675, 0.5046, 0.1567, 0.9342, 0.0240, 0.3140],
        [0.5244, 0.4222, 0.3141, 0.1090, 0.0731, 0.6240, 0.4609],
        [0.4562, 0.0596, 0.0075, 0.2872, 0.4589, 0.8270, 0.7244],
        [0.6782, 0.9466, 0.2326, 0.3081, 0.2343, 0.1396, 0.0155],
        [0.4447, 0.9096, 0.1040, 0.5462, 0.3803, 0.5100, 0.7364]])

In [14]:
random_tensor_B = torch.rand(size=(1,7))
random_tensor_B

tensor([[0.3656, 0.9093, 0.2969, 0.5860, 0.7770, 0.6394, 0.5200]])

In [58]:
#Multiplying the Two random Tensors
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result, result.shape

(tensor([[1.9872],
         [1.9848],
         [1.9103],
         [1.4283],
         [1.6536],
         [1.6377],
         [2.3451]]),
 torch.Size([7, 1]))

In [46]:
torch.manual_seed(0)
random_tensor_C = torch.rand(size=(7,7))
random_tensor_C

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [51]:
torch.manual_seed(0)
random_tensor_D = torch.rand(size=(1,7))
random_tensor_D

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [57]:
result = torch.matmul(random_tensor_C, random_tensor_D.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [59]:
result.device

device(type='cpu')