<a href="https://colab.research.google.com/github/otworiallan/otworiallan/blob/main/PyTorch_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


## Introduction to Tensors
### Creating Tensors

`torch.tensor()` creates a tensor with pre-existing data.

In [2]:
#scalar
scalar = torch.tensor(6)
scalar

tensor(6)

In [3]:
scalar.item()

6

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
vector[0]

tensor(1)

In [9]:
#MATRIX
MATRIX = torch.tensor([[1,2,2],[3,4,7]])
MATRIX

tensor([[1, 2, 2],
        [3, 4, 7]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1][2]

tensor(7)

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
MATRIX.size()

torch.Size([2, 3])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3,4],[4,5,6,4],[7,8,4,9]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [4, 5, 6, 4],
         [7, 8, 4, 9]]])

In [15]:
TENSOR[0][1][2]

tensor(6)

In [16]:
TENSOR.shape

torch.Size([1, 3, 4])

In [17]:
TENSOR.ndim

3

###Random tensors

In [18]:
RANDOM_TENSOR = torch.rand(size=(3,4))
RANDOM_TENSOR

tensor([[0.8822, 0.9550, 0.2481, 0.4389],
        [0.1512, 0.3776, 0.6944, 0.1992],
        [0.2246, 0.3455, 0.1031, 0.9468]])

In [19]:
ONES = torch.ones(size=(4,3))
print(ONES)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [20]:
ZEROS = torch.zeros(size=(4,3))
ZEROS

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
torch.matmul(RANDOM_TENSOR, ONES)

tensor([[2.5242, 2.5242, 2.5242],
        [1.4224, 1.4224, 1.4224],
        [1.6199, 1.6199, 1.6199]])

In [22]:
ONES.dtype

torch.float32

In [23]:
ONE_TO_TEN = torch.arange(end=11,step=1,start=1)
ONE_TO_TEN

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ONE_TO_TEN.shape, ONE_TO_TEN.ndim

(torch.Size([10]), 1)

In [25]:
ONES_LIKE_SHAPE = torch.ones(size=torch.Size([11,]))
ONES_LIKE_SHAPE

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
ONES_LIKE= torch.ones_like(input=ONES)
ONES_LIKE

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
ONES_LIKE[1][1].item()

1.0

In [28]:
ONES_LIKE_16 = ONES_LIKE.type(torch.float16)
ONES_LIKE_16


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float16)

In [29]:
ONES_LIKE_16 * ONES_LIKE

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
int_32_tensor = torch.tensor([1,2,3], dtype=None)
int_32_tensor

tensor([1, 2, 3])

In [31]:
int_32_tensor.dtype, int_32_tensor.device, int_32_tensor.shape

(torch.int64, device(type='cpu'), torch.Size([3]))

In [32]:
rand_tensor = torch.rand(size=(4,3), dtype=torch.float32)
rand_tensor

tensor([[0.8724, 0.7227, 0.4962],
        [0.2059, 0.4615, 0.8604],
        [0.5458, 0.7672, 0.5704],
        [0.2281, 0.5592, 0.8210]])

In [33]:
rand_tensor.device, rand_tensor.dtype, rand_tensor.shape

(device(type='cpu'), torch.float32, torch.Size([4, 3]))

In [34]:
print(f"Device tensor is on: {rand_tensor.device}")

Device tensor is on: cpu


In [35]:
torch.mul(rand_tensor, ZEROS)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
torch.add(rand_tensor, 24)

tensor([[24.8724, 24.7227, 24.4962],
        [24.2059, 24.4615, 24.8604],
        [24.5458, 24.7672, 24.5704],
        [24.2281, 24.5592, 24.8210]])

In [37]:
A = torch.tensor([1,2,3,4])
B = torch.tensor([4,5,6,89])
print(f"Matrix Multipliation: {torch.matmul(A,B)}")
print(f"Element_wise Multiplication: {torch.mul(A,B)}")

Matrix Multipliation: 388
Element_wise Multiplication: tensor([  4,  10,  18, 356])


In [38]:
A.shape, B.shape

(torch.Size([4]), torch.Size([4]))

In [39]:
P = torch.arange(1,21,1)
P = P.type(torch.float64)
P


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.], dtype=torch.float64)

In [40]:
torch.max(P), P.min()

(tensor(20., dtype=torch.float64), tensor(1., dtype=torch.float64))

In [41]:
torch.mean(P), (torch.sum(P))

(tensor(10.5000, dtype=torch.float64), tensor(210., dtype=torch.float64))

In [42]:
len(P)

20

In [43]:
P[P.argmax()].item()


20.0

In [44]:
t = torch.tensor(((1,2,3),(4,5,6)))
t.shape

torch.Size([2, 3])

In [45]:
T= t.reshape(shape=(3,2))
T.shape

torch.Size([3, 2])

In [46]:
T[:][:]

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [47]:
torch.stack([T,T,T,T], dim=1)


tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[3, 4],
         [3, 4],
         [3, 4],
         [3, 4]],

        [[5, 6],
         [5, 6],
         [5, 6],
         [5, 6]]])

In [48]:
s = torch.rand(size=(1,1,1,1,4), dtype=torch.float64)

s

tensor([[[[[0.7534, 0.4874, 0.8867, 0.8111]]]]], dtype=torch.float64)

In [49]:
torch.unsqueeze(s, 5)

tensor([[[[[[0.7534],
            [0.4874],
            [0.8867],
            [0.8111]]]]]], dtype=torch.float64)

In [50]:
s.shape

torch.Size([1, 1, 1, 1, 4])

In [51]:
torch.permute(s, (4,0,1,2,3)).shape

torch.Size([4, 1, 1, 1, 1])

In [52]:
s.permute(4,0,1,2,3)

tensor([[[[[0.7534]]]],



        [[[[0.4874]]]],



        [[[[0.8867]]]],



        [[[[0.8111]]]]], dtype=torch.float64)

In [53]:
x = torch.arange(start=1, end=10, step=1).reshape(shape=(1,3,3))
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [54]:
x[0,2,2].item(), x.dtype

(9, torch.int64)

In [55]:
x[0,2,2].item()

9

In [56]:
x[0,:,2]

tensor([3, 6, 9])

In [57]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1,10,1)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [58]:
array = array + 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [59]:
array[0] = 19
array, tensor

(array([19,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [60]:
tensor = torch.ones(size=(1,3,3))
tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [61]:
numpy_tensor = tensor.numpy()
numpy_tensor.dtype, tensor.dtype

(dtype('float32'), torch.float32)

In [62]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]),
 array([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]], dtype=float32))

In [63]:
import torch

RANDOM_SEED = 41
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(size=(4,3))

torch.manual_seed(RANDOM_SEED + 1)
random_tensor_B = torch.rand(size=(4,3))

print(random_tensor_A)
print(random_tensor_B)


tensor([[0.2364, 0.2266, 0.8005],
        [0.1692, 0.2650, 0.7720],
        [0.1282, 0.7452, 0.8045],
        [0.6357, 0.5896, 0.6933]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [64]:
!nvidia-smi

Thu Nov  7 14:02:16 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [67]:
torch.cuda.is_available()

True

In [68]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [69]:
torch.cuda.device_count()

1

In [72]:
x.device

device(type='cpu')

In [73]:
!nvidia-smi

Thu Nov  7 14:14:48 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [82]:
x = torch.rand(size=(3,2), device=device)
x

tensor([[0.9877, 0.1289],
        [0.5621, 0.5221],
        [0.7445, 0.5955]], device='cuda:0')

In [83]:
x.device


device(type='cuda', index=0)

In [87]:
x.cpu().numpy()

array([[0.98771864, 0.12889965],
       [0.56210417, 0.522108  ],
       [0.7444776 , 0.59547687]], dtype=float32)