<a href="https://colab.research.google.com/github/otworiallan/otworiallan/blob/main/PyTorch__Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import torch

In [45]:
random_tensor_A = torch.rand(size=(7,7), device="cpu")
random_tensor_A

tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
        [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])

In [46]:
random_tensor_B = torch.rand(size=(1,7), device="cpu")
random_tensor_B

tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]])

In [47]:
#Multiplying the Two random Tensors
result = torch.matmul(random_tensor_A, random_tensor_B.T)
result, result.shape

(tensor([[1.1061],
         [0.9868],
         [1.8999],
         [0.7716],
         [1.3174],
         [1.6353],
         [1.7395]]),
 torch.Size([7, 1]))

In [48]:
torch.manual_seed(0)
random_tensor_C = torch.rand(size=(7,7), device="cpu")
random_tensor_C

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [49]:
torch.manual_seed(0)
random_tensor_D = torch.rand(size=(1,7), device="cpu")
random_tensor_D

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [50]:
result = torch.matmul(random_tensor_C, random_tensor_D.T)
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [51]:
result.device

device(type='cpu')

#Random Seed on GPU


In [52]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [53]:
torch.cuda.manual_seed(1243)

random_tensor_E = torch.rand(size=(2,3), device=device)
random_tensor_E, random_tensor_E.device


(tensor([[0.3465, 0.0589, 0.5064],
         [0.7421, 0.7305, 0.9400]], device='cuda:0'),
 device(type='cuda', index=0))

In [54]:
torch.cuda.manual_seed(1234)
random_tensor_F = torch.rand(size=(2,3), device=device)
random_tensor_F, random_tensor_F.device

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 device(type='cuda', index=0))

In [55]:
result = torch.matmul(random_tensor_E, random_tensor_F.T)
result, result.size()

(tensor([[0.3676, 0.7378],
         [1.2024, 1.6039]], device='cuda:0'),
 torch.Size([2, 2]))

In [56]:
torch.max(result), result.max()

(tensor(1.6039, device='cuda:0'), tensor(1.6039, device='cuda:0'))

In [57]:
torch.min(result), result.min()

(tensor(0.3676, device='cuda:0'), tensor(0.3676, device='cuda:0'))

In [58]:
torch.manual_seed(7)
random_tensor_G = torch.rand(size=(1,1,1,10), device="cpu")
random_tensor_G

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

In [59]:
#squeeze random_tensor_G
random_tensor_G.squeeze(), random_tensor_G.squeeze().shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))